accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.BlogView.as_view(), name="blog"),
    path('post/<int:post_id>/', views.PostView.as_view(), name="post"),
    path('post/comment-reply/<int:post_id>/<int:comment_id>', views.CommentReplyView.as_view(), name="comment-reply"),
]

plant_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('home.urls')),
    path('shop/', include('shop.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
]
if settings.DEBUG:  
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)  

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, default=None ,on_delete=models.CASCADE, blank=True, null=True)
    first_name = models.CharField(max_length=50, default=None, blank=True, null=True)
    last_name = models.CharField(max_length=50, default=None, blank=True, null=True)
    phone = models.CharField(max_length=50,default=None, blank=True, null=True)
    address1 = models.CharField(max_length=50, default=None, blank=True, null=True)
    address2 = models.CharField(max_length=50, default=None, blank=True, null=True)
    state = models.CharField(max_length=50, default=None, blank=True, null=True)
    area = models.CharField(max_length=50, default=None, blank=True, null=True)
    postal_code = models.CharField(max_length=50,default=None, blank=True, null=True)
    image = models.ImageField(upload_to='images', default=None, blank=True, null=True)



accounts/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from .models import *


class RegisterForm(forms.Form):
    # first_name = forms.CharField(max_length=50,widget=forms.TextInput(attrs={'class':'form-control'}))
    # last_name = forms.CharField(max_length=50,widget=forms.TextInput(attrs={'class':'form-control'}))
    username = forms.CharField(max_length=50,widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter your username'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':'Enter your email'}))
    phone = forms.CharField(max_length=17, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Example: 09123456789'}))
    passwordd = forms.CharField(max_length=50,widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Enter your password'}))
    
    
    def clean_email(self):
        email = self.cleaned_data['email']
        user = User.objects.filter(email=email).exists()
        if user:
            raise ValidationError('this email is already registered !!')
        return email
    
    def clean_username(self):
        username = self.cleaned_data['username']
        user = User.objects.filter(username=username).exists()
        if user:
            raise ValidationError('this username is already taken !!')
        return username
    
    
class LoginForm(forms.Form):
    username = forms.CharField(max_length=50)
    password = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'placeholder':'Enter your password'}))


class UserProfileForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'enter username',}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':'enter email',}))
    
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name','phone', 'address1', 'address2', 'area', 'state', 'postal_code', 'image')

        widgets = {
            'first_name' : forms.TextInput(attrs={'class':'form-control', 'placeholder':'enter your first name',}),
            'last_name' : forms.TextInput(attrs={'class':'form-control', 'placeholder':'enter your last name',}),
            'phone' : forms.TextInput(attrs={'class':'form-control', 'placeholder':'enter phone number',}),
            'address1' : forms.TextInput(attrs={'class':'form-control', 'placeholder':'',}),
            'address2' : forms.TextInput(attrs={'class':'form-control', 'placeholder':'',}),
            'area' : forms.TextInput(attrs={'class':'form-control', 'placeholder':'',}),
            'state' : forms.TextInput(attrs={'class':'form-control', 'placeholder':'',}),
            'postal_code' : forms.TextInput(attrs={'class':'form-control', 'placeholder':'',}),
            'image': forms.FileInput()
        }

accounts/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import *
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import *


class RegisterView(View):
    
    form_class = RegisterForm
    
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)
    
    def get(self, request):
        return render(request, 'accounts/register.html', context={'form':self.form_class()})
    
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = User.objects.create_user(username=cd['username'], email=cd['email'], password=cd['passwordd'])
            phone=cd['phone']
            profile = Profile.objects.filter(user = user)[0]
            profile.phone = phone
            profile.save()
            # profile = Profile.objects.create(user = user, phone = phone)

            login(request, user)
            return redirect('home:home')
        
        return render(request, 'accounts/register.html', context={'form': form})
    
    
class LoginView(View):

    form_class = LoginForm
    
    def setup(self, request, *args, **kwargs):      
        self.next = request.GET.get('next', None)
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        return render(request, 'accounts/login.html', context={'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                request, username=cd['username'], password=cd['password'])
            if user is not None:
                login(request, user)
                # messages.success(request, 'You are in !!', 'alert alert-success')
                if self.next:
                    return redirect(self.next)
                return redirect('home:home')
            else:
                messages.error(request, 'username or password is wrong !!', 'alert alert-danger')
        return render(request, 'accounts/login.html', context={'form': form})


class LogoutView(LoginRequiredMixin ,View):
    def get(self, request):
        logout(request)
        messages.success(request, "you are out !", 'alert alert-warning')
        return redirect('home:home')
    
    
    
class ProfileView(LoginRequiredMixin, View):
    form_class = UserProfileForm
    
    def get(self, request):
        profile = Profile.objects.filter(user = request.user)[0]
        form = self.form_class(instance=request.user.profile, initial={'email':request.user.email, 'username':request.user.username})
        
        
        return render(request, 'accounts/profile.html', {'form':form})
    
    def post(self, request):
        form = self.form_class(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            cd = form.cleaned_data
            user = User.objects.get(id = request.user.id)
            user.username = cd['username']
            user.email = cd['email']
            user.save()

            messages.success(request, 'profile saved successfully.', 'alert alert-success')
            
        return redirect('accounts:profile')

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <style>
    .form-control {
      margin: 0 0 0 10px;
      width: 250px;
      height: 35px;
      background-color: white;
      border-radius: 5px;
    }
    .card-body {
      width: 200px;
      margin: 0 auto 0 30px;
    }
    .col-md-3 {
        margin: 0 auto 30px auto;
    }
    .btn-primary {
        margin: auto;
        background-color: #AE1A79;
        border: none;
        border-radius: 5px;
        padding: 10px;
    }
  </style>

  <div class="col-md-3 d-flex">
    <div class="card flex-grow-1 mb-md-0">
      <div class="card-body">
        <h3 class="card-title">Login</h3>
        <div class="form-group">
          <form action="" method="post" novalidate">
            {% csrf_token %}
            {{ form }}
            <div class="row">
                <input type="submit" class="btn btn-primary mt-4" value="login" />
                <a href="{% url 'accounts:register' %}" class="btn btn-primary mt-4">register</a>
            </div>

          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <style>

    .form-control {
        margin: 0 10px 0 10px;
        width: 350px;
        height: 35px;
        background-color: white;
        border-radius: 5px;
      }
      .card-body {
        width: 200px;
        margin: 0 auto 0 30px;
      }
      .col-md-3 {
          margin: 0 auto 30px auto;
      }
      .btn-primary {
          margin: auto;
          background-color: green;
          border: none;
          border-radius: 5px;
          padding: 10px;
      }
      .main-row {
        display: grid;
        grid-template-column: auto auto;
      }
  </style>


<div class="container rounded-lg bg-white mt-5 mb-5 ml-10">
    <form class="row" action="" method="post" novalidate enctype='multipart/form-data'>
        {% csrf_token %}

        <div class="col-md-3 border-right main-img">
           
            {% if form.instance.image %}
            <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                <img class="img-fluid rounded mt-5" src="{{form.instance.image.url}}"></div>
            {% else %}
            <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                <img class="rounded-circle mt-5" width="150px" src="https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg"></div>
            {% endif %}
            <div name ="prof_img" class="col-md-12"><label class="labels">Profile Image</label>{{form.image}}</div>

        </div>
        <div class="col-md-5 border-right">
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h4 class="text-right">Profile Info:</h4>
                </div>

                <div class="row mt-3">
                    <div class="col-md-12"><label class="labels">First name</label>{{form.first_name}}</div>
                    <div class="col-md-12"><label class="labels">Last name</label>{{form.last_name}}</div>
                    <div class="col-md-12"><label class="labels">Username</label>{{form.username}}</div>
                    <div class="col-md-12"><label class="labels">Email</label>{{form.email}}</div>
                    <div class="col-md-12"><label class="labels">Mobile Number</label>{{form.phone}}</div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h4 class="text-right">Address datailes (custem):</h4>
                </div>                
                <div class="row mt-3">
                    <div class="col-md-12"><label class="labels">Address Line 1</label>{{form.address1}}</div>
                    <div class="col-md-12"><label class="labels">Address Line 2</label>{{form.address2}}</div>
                    <div class="col-md-12"><label class="labels">Postcode</label>{{form.postal_code}}</div>
                    <div class="col-md-12"><label class="labels">State</label>{{form.state}}</div>
                    <div class="col-md-12"><label class="labels">Area</label>{{form.area}}</div>
                </div>

                <div class="mt-5 text-center"><button class="btn btnTheme w-50 fwEbold text-center text-white md-round py-3 px-4 py-md-3 px-md-4 float-right" type="submit">Save Profile</button></div>
            </div>
        </div>
    </form>
</div>

  
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <style>
    .form-control {
      margin: 0 0 0 10px;
      width: 250px;
      height: 35px;
      background-color: white;
      border-radius: 5px;
    }
    .card-body {
      width: 200px;
      margin: 0 auto 0 30px;
    }
    .col-md-4 {
        margin: 0 auto 30px auto;
    }
    .btn-primary {
        margin: auto;
        background-color: green;
        border: none;
        border-radius: 5px;
        padding: 10px;
    }
  </style>

  <div class="col-md-4 d-flex">
    <div class="card flex-grow-1 mb-md-0">
      <div class="card-body">
        <h3 class="card-title">Register</h3>
        <div class="form-group">
          <form action="" method="post" novalidate>
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="register" class="btn btn-primary mt-4" />
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}