blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.BlogView.as_view(), name="blog"),
    path('post/<int:post_id>/', views.PostView.as_view(), name="post"),
    path('post/comment-reply/<int:post_id>/<int:comment_id>', views.CommentReplyView.as_view(), name="comment-reply"),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('message/', views.MessageView.as_view(), name='message'),
]

plant_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('home.urls')),
    path('shop/', include('shop.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
]
if settings.DEBUG:  
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)  

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Post(models.Model):
    title = models.CharField(max_length=100)
    img = models.FileField(upload_to='images', default=None, blank=True, null=True)
    body = models.TextField()
    img2 = models.FileField(upload_to='images', default=None, blank=True, null=True)
    body2 = models.TextField(default=None, blank=True, null=True)
    img3 = models.FileField(upload_to='images', default=None, blank=True, null=True)
    body2 = models.TextField(default=None, blank=True, null=True)
    audio = models.FileField(upload_to='images', default=None, blank=True, null=True)
    video = models.FileField(upload_to='images', default=None, blank=True, null=True)
    writer = models.CharField(max_length=100, default=None)
    created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(blank=True, null=True)
    updated = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f'{self.slug} - {self.created}'
    
    def get_absolute_url(self):
        return reverse("blog:post", args=(self.id, self.slug))
    
    def like_counter(self):
        return self.post_votes.count()
    
    def comment_counter(self):
        return self.post_comments.count()
    
    

class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_post_votes')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_votes')
    
    def __str__(self):
        return f'{self.user} liked {self.post}' 
    
    
class PostComment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comments', default=None, blank=True, null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_comments')
    body = models.TextField(max_length=300)
    name = models.CharField(max_length=100, default='anonymous', blank=True, null=True)
    email = models.EmailField(default=None, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    is_reply = models.BooleanField(default=False)
    reply = models.ForeignKey('self', on_delete=models.CASCADE, related_name='comment_replies', blank=True, null=True)
    
    def __str__(self):
        return f'{self.user} - {self.body[:20]}'
    
    
class Subscribe(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)


blog/forms.py
from django import forms
from .models import *

class UserCommentForm(forms.ModelForm):
    class Meta:
        model = PostComment
        fields = ('body','name', 'email',)
        
        widgets = {
            'body' : forms.Textarea(attrs={'class':'form-control', 'placeholder':'comment', 'style': 'width: 200%;'}),
            'name' : forms.TextInput(attrs={'class':'form-control'}),
            'email' : forms.TextInput(attrs={'class':'form-control', 'placeholder':'enter your email...'}),
        }
        
        
class UserReplyCommentForm(forms.ModelForm):
    class Meta:
        model = PostComment
        fields = ('body','name',)
        
        widgets = {
            'body' : forms.Textarea(attrs={'class':'form-control', 'placeholder':'comment', 'style': 'height: 70px'}),
            'name' : forms.TextInput(attrs={'class':'form-control'}),
        }

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .models import *
from .forms import *
from django.views.generic import ListView
from django.core.paginator import Paginator
from django.contrib import messages
from home.forms import MessageForm


class BlogView(View):
    form_message_class = MessageForm
    def get(self, request):

        post_list = Post.objects.all()
        newest_posts = Post.objects.filter().order_by('-created')
        newest_posts = list(reversed(newest_posts))[:5]
    
        paginator = Paginator(post_list, 4)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        return render(request, 'blog/blog.html', {"page_obj": page_obj, 
                                                  'message_form':self.form_message_class, 
                                                  'newest_posts':newest_posts})
    
    def post(self, request):
        message_form = self.form_message_class(request.POST)
        
        if request.user.is_authenticated:
        
            if message_form.is_valid():
                message = message_form.save(commit=False)
                message.user = request.user
                message.save()
                messages.success(request, 'Your message saved successfully.', 'alert alert-success')
                return redirect('blog:blog')
            
        else:
            return redirect('accounts:login')

        return redirect('blog:blog')



class PostView(View):
    form_class = UserCommentForm
    form_class_reply = UserReplyCommentForm
    form_message_class = MessageForm
    def get(self, request, post_id):
        newest_posts = Post.objects.filter().order_by('-created')
        newest_posts = list(reversed(newest_posts))[:5]

        post = Post.objects.get(id=post_id)
        comments = post.post_comments.filter(is_reply=False)
        
        return render(request, 'blog/blog-detail.html', {'post': post, 'comments':comments, 'form': self.form_class(),
                                                         'message_form':self.form_message_class,
                                                               'form_reply':self.form_class_reply(), 'newest_posts':newest_posts})
        
    def post(self, request, post_id):
        post = Post.objects.get(id=post_id)
        form = self.form_class_reply(request.POST)
        message_form = self.form_message_class(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            if request.user.is_authenticated:
                new_comment.user = request.user
                if new_comment.name == 'anonymous':
                    new_comment.name = request.user.username
            new_comment.post = post
            new_comment.save()
            messages.success(request, 'your comment was sent successfuly !', 'alert alert-success')
            return redirect('blog:post', new_comment.post.id)
        
        if request.user.is_authenticated:
            
            if message_form.is_valid():
                message = message_form.save(commit=False)
                message.user = request.user
                message.save()
                messages.success(request, 'Your message saved successfully.', 'alert alert-success')
                return redirect('blog:post', post_id)
            
            else:
                return redirect('home:home')
            
        else:
            return redirect('accounts:login')
            
        


class CommentReplyView(View):
    form_class_reply = UserReplyCommentForm
    
    def post(self, request, post_id, comment_id):
        form = self.form_class_reply(request.POST)
        post = get_object_or_404(Post, id=post_id)
        comment = get_object_or_404(PostComment, id=comment_id)
        if form.is_valid():
            reply = form.save(commit=False)
            if request.user.is_authenticated:
                reply.user = request.user
                if reply.name == 'anonymous':
                    reply.name = request.user.username
            reply.post = post
            reply.is_reply = True
            reply.reply =comment
            reply.save()
            
            messages.success(request, 'your commnet was sent successfuly !', 'alert alert-success')
        return redirect('blog:post', post.id)

blog/templates/blog/blog-detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
	img.post {
		height: 400px;
		object-fit: scale-down;
	}
</style>
	<div id="pageWrapper">
		<main>
			<!-- introBannerHolder -->
			<section class="introBannerHolder d-flex w-100 bgCover" style="background-image: url({% static 'images/Capture2.png' %});">
				<div class="container">
					<div class="row">
						<div class="col-12 pt-lg-23 pt-md-15 pt-sm-10 pt-6 text-center">
							<h1 class="headingIV fwEbold playfair mb-4">Papers</h1>
							<ul class="list-unstyled breadCrumbs d-flex justify-content-center">
								<li class="mr-sm-2 mr-1"><a href="{% url 'home:home' %}">Home</a></li>
								<li class="mr-sm-2 mr-1">/</li>
								<li class="mr-sm-2 mr-1"><a href="{% url 'home:home' %}#papers">Papers</a></li>
								<li class="mr-sm-2 mr-1">/</li>
								<li class="active">{{ post.title }}</li>
							</ul>
						</div>
					</div>
				</div>
			</section>
			<!-- twoColumns -->
			<div class="twoColumns container pt-xl-23 pb-xl-20 py-lg-20 py-md-16 py-10">
				<div class="row border-bottom mb-9">
					<div class="col-12 col-lg-9 order-lg-3">
						<!-- newsBlogColumn -->
						<div class="newsBlogColumn mb-9">
							{% if post.img %}
							<div class="imgHolder mb-6">
								<img src="{{ post.img.url }}" alt="image description" class="img-fluid post">
							</div>
							{% endif %}
							<div class="textHolder d-flex align-items-start mb-1">
								<time class="time text-center text-uppercase py-sm-3 py-1 px-1" datetime="2019-02-03 20:00"> <strong class="fwEbold d-block mb-1">20</strong> Sep</time>
								<div class="alignLeft pl-6 w-100">
									<h2 class="headingV fwEbold mb-2">{{ post.title }}</h2>
									<span class="postBy d-block pb-6 mb-3">Post by: {{ post.writer }}</span>
								</div>
							</div>
							<p class="mb-5">{{ post.body }}</p>
							{% if post.img2 %}
							<div class="imgHolder mb-5">
								<img src="{{ post.img2.url }}" alt="image description" class="img-fluid post">
							</div>
							{% endif %}
							{% if post.body2 %}
							<p class="mb-5">{{ post.body2 }}</p>
							{% endif %}
							{% if post.img3 %}
							<div class="imgHolder mb-5">
								<img src="{{ post.img3.url }}" alt="image description" class="img-fluid post">
							</div>
							{% endif %}
							{% if post.body3 %}
							<p class="mb-5">{{ post.body3 }}</p>
							{% endif %}
						</div>
					</div>

						<div class="col-12 col-lg-3 order-lg-1">
							<!-- sidebar -->
							<aside id="sidebar">
	
								<section class="widget overflow-hidden mb-md-6 mb-3">
									<h3 class="headingVII fwEbold text-uppercase mb-4">ARCHIVES</h3>
									<ul class="list-unstyled archiveList mb-0">
										{% for post in newest_posts %}
										<li class="mb-3"><a href="{% url 'blog:post' post.id %}" class="d-block">{{post.title}}</a></li>
										{% endfor %}
									</ul>
								</section>
								<!-- widget -->
								<section class="widget overflow-hidden mb-md-5 mb-3">
									<h3 class="headingVII fwEbold text-uppercase mb-4">CATEGORIES</h3>
									<ul class="list-unstyled archiveList mb-0">
										<li class="mb-3"><a href="javascript:void(0);" class="d-block">Creative Ai</a></li>
										<li class="mb-3"><a href="javascript:void(0);" class="d-block">Industry</a></li>
										<li class="mb-3"><a href="javascript:void(0);" class="d-block">Data</a></li>
										<li class="mb-3"><a href="javascript:void(0);" class="d-block">Machine Learning</a></li>
									</ul>
								</section>
	
							</aside>
						</div>

				</div>
				{% comment %} <div class="row">
					<div class="col-12">
						<!-- socialNetworkList -->
						<ul class="list-unstyled socialNetworkList d-flex flex-nowrap mb-5">
							<li class="text-uppercase mr-12">SHARE THIS POST:</li>
							<li class="mr-4"><a href="javascript:void(0);" class="fab fa-facebook-f"></a></li>
							<li class="mr-4"><a href="javascript:void(0);" class="fab fa-google-plus-g"></a></li>
							<li class="mr-4"><a href="javascript:void(0);" class="fab fa-twitter"></a></li>
							<li class="mr-4"><a href="javascript:void(0);" class="fab fa-pinterest-p"></a></li>
						</ul>
					</div>
				</div> {% endcomment %}
				<div class="row mb-10">
					<div class="col-12 border-bottom">
						<!-- commentsBlock -->
						<div class="commentsBlock overflow-hidden mb-2">
							<h4 class="headingVII text-uppercase mb-5">{{ post.comment_counter }} COMMENTS</h4>
							<!-- commentArea -->


							{% for comment in comments %}
							<article class="commentArea overflow-hidden d-flex align-items-start mb-6">
								{% if request.user.is_authenticated %}
								<div class="img rounded-circle pr-7"><img src="{{comment.user.profile.image.url}}" alt="image description" class="rounded-lg img-fluid"></div>
								{% endif %}

								<div class="txtHolder border px-2 py-2">
									<span class="commentDate d-block mb-2"><a href="javascript:void(0);">{{ comment.name }}</a>
										{{ comment.created }}
									<p class="mb-1">{{ comment.body }}</p>
								</div>
							</article>

							<div class="row g-3">
								<div class="col-12">
									<div class="commentFormArea">
										<form class="commentform" action="{% url 'blog:comment-reply' post.id comment.id %}" method="post" novalidate>
											<div class="d-flex flex-wrap row1 mb-md-5">
												<div class="form-group coll mb-5">
													{% csrf_token %}
													{{ form_reply }}
													<input type="submit" value="Reply" class="reply btn btnTheme text-white px-2 py-md-2 px-md-2">
												</div>
											</div>
										</form>
									</div>
								</div>
							</div>

							{% with replies=comment.comment_replies.all %}
        					{% for reply in comment.comment_replies.all %}		
							<div class="commentOneLevel pl-md-20 pl-sm-10 pl-0 mb-9">
								<article class="commentArea overflow-hidden d-flex align-items-start mb-2">
									<div class="txtHolder border px-2 py-2">
										<span class="commentDate d-block mb-2"><a href="javascript:void(0);">{{ reply.name }}</a>{{ reply.created }}</span>
										<p class="mb-1">{{ reply.body }}</p>
									</div>
								</article>
							</div>
							{% endfor %}
							{% endwith %}

							{% endfor %}
							
						</div>
					</div>
				</div>



				<div class="row">
					<div class="col-12">
						<!-- commentFormArea -->
						<div class="commentFormArea">
							<h2 class="headingVII text-uppercase mb-5">Leave A Comment</h2>
							<form class="commentform" method="post" novalidate>
								<div class="d-flex flex-wrap row1 mb-md-5">
									<div class="form-group coll mb-5">
										{% csrf_token %}
										{{ form }}
									</div>
								</div>
								<button type="submit" class="btn btnTheme btnShop md-round fwEbold text-white py-3 px-4 py-md-3 px-md-4">Post Now <i class="fas fa-arrow-right ml-2"></i></button>
							</form>
						</div>
					</div>
				</div>
			</div>



			<div class="container mb-lg-24 mb-md-16 mb-10">


				<!-- subscribeSecBlock -->
				<section class="subscribeSecBlock bgCover col-12 pt-lg-24 pb-lg-12 pt-md-16 pb-md-8 py-10" style="background-image: url({% static 'images/sd.png' %})">
					<header class="col-12 mainHeader mb-9 text-center">
						<h1 class="headingIV playfair fwEblod mb-4">Send Us a Message</h1>
						<p class="mb-6">Send Us a Message and we'll call you for Free Consulation :)</p>
					</header>
					{% comment %} <form class="emailForm1 mx-auto overflow-hidden d-flex flex-wrap">
						<input type="email" class="form-control px-4 border-0" placeholder="Enter your mail...">
						<button type="submit" class="btn btnTheme btnShop fwEbold text-white py-3 px-4 py-md-3 px-md-4">Submit<i class="fas fa-arrow-right ml-2"></i></button>
					</form> {% endcomment %}
					

					<form action="" method="post" novalidate class="mess row d-flex justify-content-center">
				
						{% csrf_token %}
						{{ message_form }}
						<button type="submit" class="mess btn btnTheme btnShop md-round fwEbold text-white py-3 px-4 py-md-3 px-md-4 ml-5">Post Now <i class="fas fa-arrow-right ml-2"></i></button>
					</form>

				</section>
			</div>
		</main>
	</div>
{% endblock content %}

blog/templates/blog/blog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
	img.cat {
	  height: 250px;
	  object-fit: scale-down;
	}
	img.post {
		height: 250px;
		object-fit: scale-down;
	}
	.pagination {
		margin: auto;
	}
	.current {
		margin: auto;
		margin-right: 1vw;
	}
	.pag {
		margin: 0 0.3vw 0 0.3vw;
		width: 80px;
	}
</style>
		<main>
			<!-- introBannerHolder -->
			<section class="introBannerHolder d-flex w-100 bgCover" style="background-image: url({% static 'images/Capture2.png' %});">
				<div class="container">
					<div class="row">
						<div class="col-12 pt-lg-23 pt-md-15 pt-sm-10 pt-6 text-center">
							<h1 class="headingIV fwEbold playfair mb-4">Papers</h1>
							<ul class="list-unstyled breadCrumbs d-flex justify-content-center">
								<li class="mr-2"><a href="{% url 'home:home' %}">Home</a></li>
								<li class="mr-2">/</li>
								<li class="active">Papers</li>
							</ul>
						</div>
					</div>
				</div>
			</section>
			<!-- twoColumns -->
			<div class="twoColumns container pt-lg-23 pb-lg-20 pt-md-16 pb-md-4 pt-10 pb-4">
				<div class="row">
					<div class="col-12 col-lg-9 order-lg-3">
						<!-- content -->
						<article id="content">
							<!-- newsBlogColumn -->
							{% for post in page_obj %}
							<div class="newsBlogColumn mb-md-9 mb-6">
								<div class="imgHolder position-relative mb-6">
									<a href="{% url 'blog:post' post.id %}">
										{% if post.img %}
										<img src="{{ post.img.url }}" alt="image description" class="img-fluid post">
										{% endif %}
									</a>
								</div>
								<div class="textHolder d-flex align-items-start">
									<time class="time text-center text-uppercase py-sm-2 py-0 px-1" datetime=""> <strong class="fwEbold d-block mb-1">{{ post.created.date }}</strong></time>
									<div class="alignLeft pl-sm-6 pl-3">
										<h2 class="headingV fwEbold mb-2"><a href="{% url 'blog:post' post.id %}">{{ post.title }}</a></h2>
										<span class="postBy d-block pb-sm-6 pb-2 mb-3">Post by: <a href="">{{ post.writer }}</a></span>
										<p class="mb-0">{{ post.body|slice:":80" }}...</p>
									</div>
								</div>
							</div>
							{% endfor %}

							<div class="pagination col-12 pt-3 mb-lg-0 mb-md-6 mb-3">
								<ul class="step-links list-unstyled pagination d-flex justify-content-center align-items-end">
									{% if page_obj.has_previous %}
										<a class="pag" href="?page=1">&laquo; first</a>
										<a class="pag" href="?page={{ page_obj.previous_page_number }}">previous</a>
									{% endif %}
							
									<span class="current">
										Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
									</span>
							
									{% if page_obj.has_next %}
										<a class="pag" href="?page={{ page_obj.next_page_number }}">next</a>
										<a class="pag" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
									{% endif %}
								</ul>
							</div>



						</article>
					</div>
					<div class="col-12 col-lg-3 order-lg-1">
						<!-- sidebar -->
						<aside id="sidebar">

							<section class="widget overflow-hidden mb-md-6 mb-3">
								<h3 class="headingVII fwEbold text-uppercase mb-4">ARCHIVES</h3>
								<ul class="list-unstyled archiveList mb-0">
									{% for post in newest_posts %}
									<li class="mb-3"><a href="{% url 'blog:post' post.id %}" class="d-block">{{post.title}}</a></li>
									{% endfor %}
								</ul>
							</section>
							<!-- widget -->
							<section class="widget overflow-hidden mb-md-5 mb-3">
								<h3 class="headingVII fwEbold text-uppercase mb-4">CATEGORIES</h3>
								<ul class="list-unstyled archiveList mb-0">
									<li class="mb-3"><a href="javascript:void(0);" class="d-block">Creative</a></li>
									<li class="mb-3"><a href="javascript:void(0);" class="d-block">Fashion</a></li>
									<li class="mb-3"><a href="javascript:void(0);" class="d-block">Image</a></li>
									<li class="mb-3"><a href="javascript:void(0);" class="d-block">Photography</a></li>
									<li class="mb-3"><a href="javascript:void(0);" class="d-block">Travel</a></li>
									<li class="mb-3"><a href="javascript:void(0);" class="d-block">Videos</a></li>
									<li class="mb-3"><a href="javascript:void(0);" class="d-block">WordPress</a></li>
								</ul>
							</section>

						</aside>
					</div>
				</div>
			</div>
			<div class="container mb-lg-24 mb-md-16 mb-10">
				<!-- subscribeSecBlock -->
				<section class="subscribeSecBlock bgCover col-12 pt-lg-24 pb-lg-12 pt-md-16 pb-md-8 py-10" style="background-image: url({% static 'images/sd.png' %})">
					<header class="col-12 mainHeader mb-9 text-center">
						<h1 class="headingIV playfair fwEblod mb-4">Send Us a Message</h1>
						<p class="mb-6">Send Us a Message and we'll call you for Free Consulation :)</p>
					</header>
					<form action="" method="post" novalidate class="mess row d-flex justify-content-center">
				
						{% csrf_token %}
						{{ message_form }}
						<button type="submit" class="mess btn btnTheme btnShop md-round fwEbold text-white py-3 px-4 py-md-3 px-md-4 ml-5">Post Now <i class="fas fa-arrow-right ml-2"></i></button>
					</form>
				</section>
			</div>
		</main>
	</div>
{% endblock content %}