accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.BlogView.as_view(), name="blog"),
    path('post/<int:post_id>/', views.PostView.as_view(), name="post"),
    path('post/comment-reply/<int:post_id>/<int:comment_id>', views.CommentReplyView.as_view(), name="comment-reply"),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('message/', views.MessageView.as_view(), name='message'),
]

plant_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('home.urls')),
    path('shop/', include('shop.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
]
if settings.DEBUG:  
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)  

templates/base.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <head>
    <!-- set the encoding of your site -->
    <meta charset="utf-8" />
    <!-- set the Compatible of your site -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- set the page title -->
    <title>IOTA Technology</title>
    <link rel="stylesheet" href="{% static 'styles/css/fontawesome.css' %}" />
    <link href="{% static 'styles/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'styles/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'styles/css/solid.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'styles/fontawesome.js' %}"></script>
    <script src="{% static 'styles/solid.js' %}"></script>
    <script src="{% static 'styles/brands.js' %}"></script>
    <!-- include the site Google Fonts stylesheet -->
    <link
      href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700%7CRoboto:300,400,500,700,900&display=swap"
      rel="stylesheet"
    />
    <link src="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- include the site bootstrap stylesheet -->
    <link rel="stylesheet" href="{% static 'styles/css/bootstrap.css' %}" />
    <!-- include the site fontawesome stylesheet -->
    
    {% comment %} <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet"> {% endcomment %}
    <!-- include the site stylesheet -->
    <link rel="stylesheet" href="{% static 'styles/style.css' %}" />
    <!-- include theme plugins setting stylesheet -->
    <link rel="stylesheet" href="{% static 'styles/css/plugins.css' %}" />
    <!-- include theme color setting stylesheet -->
    <link rel="stylesheet" href="{% static 'styles/css/color.css' %}" />
    <!-- include theme responsive setting stylesheet -->
    <link rel="stylesheet" href="{% static 'styles/css/responsive.css' %}" />

    <style>
      input.price {
        background-color : white;
        width: 80px;
        height: 35px;
      }
      img.top-rating {
        height: 80px;
        object-fit: scale-down;
        
      }
      .form-control:focus {
        background-color: white;
      }
      input.search {
        margin: 10px 0 20px 0;
        color: green;
        border-color: green;
      }
      input.search::on-hover {
        background-color: green;
      }
      input.reply{
        margin-top: 5px;
      }
      .numitems {
        font-size: 1px;
      }
      .quantity{
        display: inline-block;
        font-weight: 700;
        padding-right:10px;
        
      
      }
      .chg-quantity{
        width: 12px;
        cursor: pointer;
        display: block;
        margin-top: 5px;
        transition:.1s;
      }
      
      .chg-quantity:hover{
        opacity: .6;
      }

      img.cat {
        height: 270px;
        object-fit: scale-down;
      }
      .pagination {
        margin: auto;
      }
      .current {
        margin: auto;
        margin-right: 1vw;
      }
      .pag {
        margin: 0 0.3vw 0 0.3vw;
        width: 80px;
      }
    </style>
    <script type="text/javascript">
      var user = '{{request.user}}'
  
      function getToken(name) {
          var cookieValue = null;
          if (document.cookie && document.cookie !== '') {
              var cookies = document.cookie.split(';');
              for (var i = 0; i < cookies.length; i++) {
                  var cookie = cookies[i].trim();
                  // Does this cookie string begin with the name we want?
                  if (cookie.substring(0, name.length + 1) === (name + '=')) {
                      cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                      break;
                  }
              }
          }
          return cookieValue;
      }
      var csrftoken = getToken('csrftoken')
  
      function getCookie(name) {
          // Split cookie string and get all individual name=value pairs in an array
          var cookieArr = document.cookie.split(";");
  
          // Loop through the array elements
          for(var i = 0; i < cookieArr.length; i++) {
              var cookiePair = cookieArr[i].split("=");
  
              /* Removing whitespace at the beginning of the cookie name
              and compare it with the given string */
              if(name == cookiePair[0].trim()) {
                  // Decode the cookie value and return
                  return decodeURIComponent(cookiePair[1]);
              }
          }
  
          // Return null if not found
          return null;
      }
      var cart = JSON.parse(getCookie('cart'))
  
      if (cart == undefined){
        cart = {}
        console.log('Cart Created!', cart)
        document.cookie ='cart=' + JSON.stringify(cart) + ";domain=;path=/"
      }
      console.log('Cart:', cart)
    
    </script>
  </head>
  <body>

    {% include 'navbar.html' %}
    {% include 'messages.html' %}
    {% block content %}

    
    {% endblock content %}
    {% include 'footer.html' %}
<!-- include jQuery library -->
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- include bootstrap popper JavaScript -->
<script src="{% static 'js/popper.min.js' %}"></script>
<!-- include bootstrap JavaScript -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- include custom JavaScript -->
<script src="{% static 'js/jqueryCustome.js' %}"></script>
<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
  </body>
</html>

templates/footer.html
<aside class="footerHolder overflow-hidden bg-lightGray pt-xl-23 pb-xl-8 pt-lg-10 pb-lg-8 pt-md-12 pb-md-8 pt-10">
  <div class="container">
    <div class="row">
      <div class="col-12 col-sm-6 col-lg-4 mb-lg-0 mb-4">
        <h3 class="headingVI fwEbold text-uppercase mb-7">Contact Us</h3>
        <ul class="list-unstyled footerContactList mb-3">
          <li class="mb-3 d-flex flex-nowrap">
            <span class="icon icon-phone mr-3"></span>
            <span class="leftAlign"
              >Phone : <a href="javascript:void(0);">(+098) 0921 - 5723628</a></span
            >
          </li>
          <li class="email d-flex flex-nowrap">
            <span class="icon icon-email mr-2"></span>
            <span class="leftAlign"
              >Email:
              <a href="javascript:void(0);">iota.tech24@gmail.com</a></span
            >
          </li>
        </ul>
        <ul class="list-unstyled followSocailNetwork d-flex flex-nowrap">
          <li class="fwEbold mr-xl-11 mr-md-8 mr-3">Follow us:</li>
          <li class="mr-xl-6 mr-md-5 mr-2">
            <a href="javascript:void(0);" class="fab fa-telegram"></a>
          </li>
          <li class="mr-xl-6 mr-md-5 mr-2">
            <a href="javascript:void(0);" class="fab fa-linkedin"></a>
          </li>
          <li class="mr-xl-6 mr-md-5 mr-2">
            <a href="javascript:void(0);" class="fab fa-instagram"></a>
          </li>
          <li class="mr-2">
            <a href="javascript:void(0);" class="fab fa-whatsapp"></a>
          </li>
        </ul>
      </div>
      <div class="col-12 col-sm-6 col-lg-3 pl-xl-14 mb-lg-0 mb-4">
        <h3 class="headingVI fwEbold text-uppercase mb-6">Information</h3>
        <ul class="list-unstyled footerNavList">
          <li class="mb-1"><a href="javascript:void(0);">About us</a></li>
          <li class="mb-2"><a href="javascript:void(0);">Papers</a></li>
          <li class="mb-2"><a href="javascript:void(0);">Contact us</a></li>
          <li class="mb-2"><a href="javascript:void(0);">Catelog</a></li>
        </ul>
      </div>
      <div class="col-12 col-sm-6 col-lg-3 pl-xl-12 mb-lg-0 mb-4">
        <h3 class="headingVI fwEbold text-uppercase mb-7">My Account</h3>
        <ul class="list-unstyled footerNavList">
          <li class="mb-1"><a href="javascript:void(0);">My account</a></li>
          <li class="mb-2"><a href="javascript:void(0);">Discount</a></li>
          <li class="mb-2"><a href="javascript:void(0);">Orders history</a></li>
          <li><a href="javascript:void(0);">Personal information</a></li>
        </ul>
      </div>
      <div class="col-12 col-sm-6 col-lg-2 pl-xl-18 mb-lg-0 mb-4">
        <h3 class="headingVI fwEbold text-uppercase mb-5">PRODUCTS</h3>
        <ul class="list-unstyled footerNavList">
          <li class="mb-2"><a href="javascript:void(0);">Soft Ware</a></li>
          <li class="mb-2"><a href="javascript:void(0);">Data Analysis</a></li>
          <li class="mb-2"><a href="javascript:void(0);">Digital Models</a></li>
        </ul>
      </div>
    </div>
  </div>
</aside>

<footer id="footer" class="overflow-hidden bg-dark">
  <div class="container">
    <div class="row">
      <div class="col-12 copyRightHolder v-II text-center pt-md-3 pb-md-4 py-2">
        <p class="mb-0">
          Coppyright 2024 by <a href="javascript:void(0);">IOTA Technology</a> -
          All right reserved
        </p>
      </div>
    </div>
  </div>
</footer>

templates/messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/navbar.html
{% load static %}
<header id="header" class="position-relative sticky position-sticky" style="background: white;">
    <!-- headerHolderCol -->
    <div class="headerHolderCol pt-lg-4 pb-lg-5 py-3">
        <div class="container">
            <div class="row">
                <div class="col-12 col-sm-4">
                    <a href="javascript:void(0);" class="tel d-flex align-items-end"><i class="icon-call mr-2"></i>  Hotline: +98 0921 - 5723628</a>
                </div>
                <div class="col-12 col-sm-4 text-center">
                    <span class="txt d-block">Wellcome To IOTA Tech</span>
                </div>
                <div class="col-12 col-sm-4">
                    <!-- langListII -->
                    <ul class="nav nav-tabs langListII justify-content-end border-bottom-0">
                        <li class="dropdown">
                            <span>Mode: </span>
                            <a class="d-inline dropdown-toggle text-uppercase" data-toggle="dropdown" href="javascript:void(0);" role="button" aria-haspopup="true" aria-expanded="false">Light</a>
                            <div class="dropdown-menu text-uppercase pl-4 pr-4 border-0">
                                <a class="dropdown-item" href="javascript:void(0);">Light</a>
                                {% comment %} <a class="dropdown-item" href="javascript:void(0);">Dark</a> {% endcomment %}
                            </div>
                        </li>
                        <li class="dropdown m-0">
                            <span>Languages: </span>
                            <a class="d-inline dropdown-toggle text-uppercase" data-toggle="dropdown" href="javascript:void(0);" role="button" aria-haspopup="true" aria-expanded="false">EN</a>
                            <div class="dropdown-menu pl-4 pr-4">
                                <a class="dropdown-item" href="javascript:void(0);">English</a>
                                {% comment %} <a class="dropdown-item" href="javascript:void(0);">Farsi</a> {% endcomment %}
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- headerHolder -->
    <div class="headerHolder container" style="background: white;">
        <div class="row">
            <div class="col-6 col-sm-2">
                <!-- mainLogo -->
                <div class="logo pt-1">
                    <a href="home.html"><img src="{% static 'images/logo.png' %}" alt="Botanical" class="img-fluid"></a>
                </div>
            </div>
            <div class="col-6 col-sm-7 col-lg-8 static-block">
                <!-- mainHolder -->
                <div class="mainHolder pt-lg-5 pt-3 justify-content-center">
                    <!-- pageNav2 -->
                    <nav class="navbar navbar-expand-lg navbar-light p-0 pageNav2 position-static">
                        <button type="button" class="navbar-toggle collapsed position-relative" data-toggle="collapse" data-target="#navbarNav" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarNav">
                            <ul class="navbar-nav mx-auto text-uppercase d-inline-block">
                                <li class="nav-item active dropdown">
                                    <a href="{% url 'home:home' %}" class="dropdown-toggle d-block">home</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a href="{% url 'home:home' %}#services" class="dropdown-toggle d-block">Services</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a href="{% url 'home:home' %}#projects" class="dropdown-toggle d-block">Projects</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="dropdown-toggle d-block" href="{% url 'blog:blog' %}">Papers</a>
                                </li>
                                <li class="nav-item">
                                    <a class="d-block" href="{% url 'home:about' %}">About</a>
                                </li>
                                <li class="nav-item">
                                    <a class="d-block" href="{% url 'home:contact' %}">contact</a>
                                </li>
                                <li class="nav-item" style="margin: 0 0 0 0px">
                                    {% if request.user.is_authenticated %}
                                    <a class="d-block" href="{% url 'accounts:logout' %}">logout</a>
                                    {% else %}
                                    <a class="d-block" href="{% url 'accounts:login' %}">log/sign in</a>
                                    {% endif %}
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
            <div class="col-sm-4 col-lg-2">
                <!-- wishListII -->
                <ul class="nav nav-tabs wishListII pt-5 justify-content-end border-bottom-0">
                    {% comment %} <li class="nav-item ml-0"><a class="nav-link icon-search" href="javascript:void(0);"></a></li> {% endcomment %}
                    {% comment %} <li class="nav-item"><a class="nav-link position-relative icon-cart" href="{% url 'shop:cart' %}"> {% endcomment %}
                        {% comment %} <span id="cart-total" class="num  numitems rounded d-block">{{cartItems}}</span></a></li> {% endcomment %}
                    <li class="nav-item"><a class="nav-link icon-profile" href="{% url 'accounts:profile' %}"></a></li>

                </ul>
            </div>
        </div>
    </div>
</header>